Create dz-4.py
eugene-okulik/SmirnovT pull request #3
Opened 2024-01-12 06:42 UTC by Timuchi

2024-01-12 08:20 UTC, eugene-okulik requested changes
Всё хорошо, но проверку на внимательность не прошел )))

2024-01-12 08:20 UTC, eugene-okulik commented on homework/timur_smirnov/Homework_4/dz-4.py
> +my_dict['dict']['i am a tuple'] = 'primer'
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнил, как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

2024-01-12 09:17 UTC, Timuchi commented on homework/timur_smirnov/Homework_4/dz-4.py
> +my_dict['dict']['i am a tuple'] = 'primer'
Я сначало так и сделал :), но подумал, что это как-то не верно выглядит и переделал :)

2024-01-14 11:28 UTC, eugene-okulik approved these changes
Отлично переделал. Обычно переделывают тоже неправильно )))  
Здесь я это сделал, чтобы обратить внимание на:

1.  то, что ключом словаря может быть кортеж
2.  то, как выглядит кортеж с одним элементом

2024-01-14 11:28 UTC, merged